### ISSUE TITLE
Spam in console - bug

### ISSUE THREAD

**Issue by vavraCZe** [cpw/compactsolars#12]
Server have 1 - 13TPS with this bug.

http://lipovcan.cz:7777/wesonokako.avrasm

**Comment by maciekmm** [comment]
I confirm it it happens with mcpc+ L19

**Comment by vemacs** [comment]
still an issue. confirming with MCPC+ L15

**Comment by agaricusb** [comment]
@vavraCZe This has been fixed in MCPC+ 1.5.x (can't recall the commit off-hand); this issue can be closed
